# Generated by Django 4.2.2 on 2023-07-02 18:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_agensi', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('no_tel', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_pegawai', models.CharField(blank=True, max_length=200, null=True)),
                ('emel', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_fasa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fokus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fokus', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gunatanahsemasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_gtn', models.CharField(blank=True, max_length=7, null=True)),
                ('no_lot', models.CharField(blank=True, max_length=11, null=True)),
                ('mukim_id', models.CharField(blank=True, max_length=6, null=True)),
                ('upi', models.CharField(blank=True, max_length=16, null=True)),
                ('gtn2', models.CharField(blank=True, max_length=50, null=True)),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('pbt_id', models.CharField(blank=True, max_length=6, null=True)),
                ('gtn1', models.CharField(blank=True, max_length=50, null=True)),
                ('teks', models.CharField(blank=True, max_length=50, null=True)),
                ('nama', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('negeri_id', models.CharField(blank=True, max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('seksyen_id', models.CharField(blank=True, max_length=9, null=True)),
                ('daerah_id', models.CharField(blank=True, max_length=4, null=True)),
                ('tahun_data', models.IntegerField(blank=True, null=True)),
                ('fcode', models.CharField(blank=True, max_length=6, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_jenis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nama_kategori', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('kod_lembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('nama_lembangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rumusankawalangunatanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nama_sublembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('rumusan_kawalan_gunatanah', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('zon_tindakan', models.CharField(blank=True, max_length=100, null=True)),
                ('kod_sublembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('rumusan_kualiti_air', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rumusankualitiair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sublembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('zon_tindakan', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('rumusan_kawalan_gunatanah', models.CharField(blank=True, max_length=100, null=True)),
                ('rumusan_kualiti_air', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('kod_sublembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Sempadanrkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nama_rkk', models.CharField(blank=True, max_length=200, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sublembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumusan_kawalan_gunatanah', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('rumusan_kualiti_air', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nama_sublembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('kod_sublembangan', models.CharField(blank=True, max_length=30, null=True)),
                ('zon_tindakan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sungai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_sungai', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_sungai', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('kod_lembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('panjang_km', models.FloatField(blank=True, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zontindakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sublembangan', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('luas_hektar', models.FloatField(blank=True, null=True)),
                ('zon_tindakan', models.CharField(blank=True, max_length=100, null=True)),
                ('rumusan_kualiti_air', models.CharField(blank=True, max_length=100, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('rumusan_kawalan_gunatanah', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('kod_sublembangan', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_projek', models.CharField(max_length=200)),
                ('mukasurat_laporan', models.CharField(blank=True, max_length=100, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('imej', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
                ('deskripsi_cadangan', models.TextField(blank=True, max_length=1000, null=True)),
                ('kod_projek', models.CharField(blank=True, max_length=50, null=True)),
                ('justifikasi_cadangan', models.TextField(blank=True, max_length=1000, null=True)),
                ('kos_pelaksanaan', models.IntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, max_length=1000, null=True)),
                ('sasaran_pencapaian', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('agensi_pelaksana', models.ManyToManyField(blank=True, related_name='+', to='projekrkk.agensi')),
                ('agensi_pembiaya', models.ManyToManyField(blank=True, related_name='+', to='projekrkk.agensi')),
                ('agensi_pemula', models.ManyToManyField(blank=True, related_name='+', to='projekrkk.agensi')),
                ('fasa', models.ManyToManyField(blank=True, related_name='+', to='projekrkk.fasa')),
                ('fokus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projekrkk.fokus')),
                ('jenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projekrkk.jenis')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projekrkk.kategori')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projekrkk.status')),
                ('sublembangan', models.ManyToManyField(blank=True, related_name='+', to='projekrkk.sublembangan')),
            ],
        ),
    ]
